### ISSUE TITLE
Replace HSeparatorDeprecated and VSeparatorDeprecated

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#805] opened 2022-10-21 03:26 UTC
Replace HSeparatorDeprecated and VSeparatorDeprecated with HSeparator and VSeparator respectively.  They should NOT be instrumented for PhET-iO (see https://github.com/phetsims/scenery/issues/1480). Then delete the deprecated classes.

HSeparatorDeprecated occurrences:
- [x] blackbody-spectrum @jbphet (done by @pixelzoom)
- [x] build-a-nucleus @Luisav1 @marlitas - see https://github.com/phetsims/build-a-nucleus/issues/63
- [x] circuit-construction-kit-common @samreid 
- [x] collision-lab @jonathanolson 
- [x] density-and-buoyancy-common @jonathanolson 
- [x] energy-skate-park @jessegreenberg 
- [x] fourier-making-waves @pixelzoom 
- [x] gas-properties @pixelzoom 
- [x] graphing-lines @pixelzoom 
- [x] graphing-quadratics @pixelzoom 
- [x] gravity-and-orbits @samreid 
- [x] hookes-law @pixelzoom 
- [x] molecule-polarity @pixelzoom 
- [x] normal-modes @pixelzoom 
- [x] projectile-motion @jbphet (done by @pixelzoom)
- [x] ratio-and-proportion @zepumph 
- [x] scenery-phet demo @pixelzoom 
- [x] sun.Carousel @pixelzoom 
- [x] trig-tour @jessegreenberg 
- [x] vector-addition @pixelzoom 
- [x] wave-interference @samreid 
- [x] xray-diffraction @pixelzoom 

VSeparatorDeprecated occurrences:
- [x] gas-properties @pixelzoom 
- [x] geometric-optics @pixelzoom 
- [x] hookes-law @pixelzoom 
- [x] scenery-phet demo @pixelzoom
- [x] sun.Carousel @pixelzoom 
- [x] sun.ComboBoxButton @jonathanolson 
- [x] trig-tour @jessegreenberg

**Comment by pixelzoom** [comment] 2022-10-21 04:17
Done with my occurrences, unassigning.

**Comment by jbphet** [comment] 2022-11-09 22:45
I updated the checkbox for build-a-nucleus, since it was assigned to me but I'm not working on that sim.  I also updated the assignees of the issue.

**Comment by samreid** [comment] 2022-11-10 19:14
Still remaining, clustered by devs:

- [ ] build-a-nucleus @Luisav1 @chrisklus
- [ ] ratio-and-proportion @zepumph
- [ ] trig-tour @jessegreenberg
- [ ] trig-tour @jessegreenberg
- [ ] energy-skate-park @jessegreenberg
- [ ] collision-lab @jonathanolson
- [ ] density-and-buoyancy-common @jonathanolson
- [ ] gravity-and-orbits @jonathanolson
- [ ] sun.ComboBoxButton @jonathanolson

**Comment by jbphet** [comment] 2022-11-10 22:04
I took a shot at sun.ComboBoxButton, but ran into problems.  It uses a `GridBox` layout, and these layouts are apparently incompatible with the new `VSeparator` classes.  I tried using an `HBox` for the layout instead, but it didn't like the default `left` align options, which is somewhat understandable, but we really *do* need some way to position the choices in the box on the left side.  I spoke with @jonathanolson about all of this, and he said that there were several ways to potentially approach the problem, and suggested not using a `VSeparator` at all in this case.  He suggested I assign it back to him for a look.  So, sorry I was unable to resolve it.  Assigning back to @jonathanolson.

**Comment by samreid** [comment] 2022-11-17 18:57
Nov 17 2022 Dev Meeting

@jonathanolson: When we need to expand cells and align things, GridBox doesn't support that.  So it could be a multi-day issue to get a good long-term solution.  But would be better to have more layout work support in advance.  But I'm not convinced ComboBoxButton should be using a separator.  That seems fragile and should be done with something else.
@pixelzoom: Just a Line?
@jonathanolson: Yes.
@kathy-phet: Can @jonathanolson prioritize this after other urgent maintenance releases are done?
@marlitas: This seems like something I could help on, I can take a look and collaborate with @jonathanolson when he has time
@kathy-phet great!

**Comment by marlitas** [comment] 2022-11-28 02:32
- Combo-box has been moved to this issue: https://github.com/phetsims/sun/issues/810
- Build a nucleus instance is waiting on my review here: https://github.com/phetsims/build-a-nucleus/issues/63
- Gridbox work mentioned in dev meeting has been moved to this issue: https://github.com/phetsims/scenery/issues/1504

Unassigning myself from this issue.

**Comment by marlitas** [comment] 2022-12-22 02:54
@jonathanolson and @zepumph, would you like me to handle the deprecated usages that are assigned to you?

-  ratio-and-proportion @zepumph
-  collision-lab @jonathanolson
-  density-and-buoyancy-common @jonathanolson

**Comment by jonathanolson** [comment] 2022-12-22 21:14
> @jonathanolson and @zepumph, would you like me to handle the deprecated usages that are assigned to you?

Sure, feel free to if you're available!

**Comment by zepumph** [comment] 2022-12-23 14:25
That would be so great thanks!

**Comment by zepumph** [comment] 2022-12-23 14:26
Let me know if you run into trouble.

**Comment by marlitas** [comment] 2023-03-07 16:20
@zepumph and @jonathanolson, the deprecated separators have been addressed in your corresponding repos.

I also deleted the deprecated separator files. If that's not the right protocol I can revert, but they are no longer being used anywhere in the codebase. 

Over to @zepumph and @jonathanolson to review your repos that I touched. The changes are straightforward. I didn't run into any complications, and screens matched before/after.

**Comment by zepumph** [comment] 2023-03-07 23:25
You commit has left a regression in RAP: 

![image](https://user-images.githubusercontent.com/6856943/223578256-84764fbb-3e85-411f-94b4-5f1487ac3335.png)


When disabled, there is no longer a dashed line. I'm not sure how you can provide that without hard coding its length (which was removed in https://github.com/phetsims/ratio-and-proportion/commit/169df9f1dc04d720d3d0dd509876c156a49edc24#diff-8ce26a7818178448309f0ea8fc0108aa25f372966ca461f2e301ef7affb23c93L63)

**Comment by marlitas** [comment] 2023-03-08 00:20
Weird... I checked that and didn't see that regression... I'll look through it again.

**Comment by marlitas** [comment] 2023-03-08 00:39
Fix pushed. Back to you @zepumph

**Comment by zepumph** [comment] 2023-03-08 01:21
Great thanks!

**Comment by samreid** [comment] 2023-04-05 20:08
I confirmed there are no more references to the deprecated separators. I updated the documentation. Closing.

**Closed by samreid** 2023-04-05 20:08 UTC
Labels: dev:phet-io, status:ready-for-review, dev:chip-away
