### ISSUE TITLE
anti-pattern for setting phetioEventSource

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#335] opened 2018-02-06 20:29 UTC
Throughout sun buttons, `phetioEventSource` is currently set in options, e.g.:

```js
  function RectangularPushButton( options ) {
    ...
    options = _.extend( {
        ...
36      phetioEventSource: this
    }, options );

    ...
46     this.buttonModel = new PushButtonModel( options );
    ...
52     RectangularButtonView.call( ..., options );
```

Problems:

(1) `phetioEventSource` is relevant only to the model, but it's being passed to the model and view.

(2) Since it's in the default options, `phetioEventSource` can be overridden by the client.

The preferred approach is to specify `phetioEventSource` only in the options for the model, e.g.:

```js
46  this.buttonModel = new PushButtonModel( _.extend( { phetioEventSource: this }, options ) ); 
```

**Comment by samreid** [comment] 2018-02-06 20:32
See parent issue https://github.com/phetsims/build-a-molecule/issues/81

**Comment by pixelzoom** [comment] 2018-02-06 22:32
This still allows the client to override `phetioEventSource`:

```js
46  this.buttonModel = new PushButtonModel( _.extend( { phetioEventSource: this }, options ) ); 
```

We should add an assertion prior to instantiating `PushButtonModel`, e.g.:

```js
assert && assert( !options. phetioEventSource, 'phetioEventSource is not an option' );
this.buttonModel = new PushButtonModel( _.extend( { phetioEventSource: this }, options ) ); 
```

**Comment by samreid** [comment] 2018-02-06 23:18
Agreed, thanks!

**Comment by samreid** [comment] 2018-02-07 04:36
Pushed fixes above, and would be good for @pixelzoom to spot check. Also, regarding lines like these in StickyToggleButtonModel.js
``js
    options = _.extend( {
      tandem: Tandem.required,
      phetioEventSource: new PhetioObject( { tandem: Tandem.optional } ) // TODO: may not be necessary if all clients are passing this in
    }, options );
```

Both call sites that call `new StickyToggleButtonModel` are passing in a `phetioEventSource`.  We don't have plans for any StickyToggleButtonModel subclasses (and there aren't any at the moment).  Do we still need the default `new PhetioObject( { tandem: Tandem.optional } )` or should we assert that it should be provided an add a comment about it?  Or if we decide it is a required argument, do you want to move it out of the options to a first-class argument?

**Comment by pixelzoom** [comment] 2018-02-07 17:25
@samreid said:
> Pushed fixes above, and would be good for @pixelzoom to spot check

Changes spot checked, they look good. 

> Also, regarding lines like these in StickyToggleButtonModel.js ...

Let's chat about this on Slack. The need for this (and my feedback) is motivated by some more general "semantic" issues about what it means for a PhetioObject to be "initialized", and whether initializing is required.

**Comment by samreid** [comment] 2018-02-07 17:36
Some notes from slack:

Creating that "default" PhetioObject is just so we don't get an undefined error when trying to make calls on it.  The data just won't go anywhere
(if a true proxy is not supplied)
otherwise we could use `if (phetioEventSource){...}`
Maybe that would be clearer?
For instance, MomentaryButtonModel.js line 46 would read: 
`options.phetioEventSource && options.phetioEventSource.startEvent( 'user', 'pressed' );` and so forth
then we would eliminate the default PhetioObject altogether

**Comment by pixelzoom** [comment] 2018-02-08 20:23
Discussion with @samreid on Zoom:

(1) I don't have a preference for whether to default `phetioEventSource` to `null` or `new PhetioObject( { tandem: Tandem.optional } )`.  Using `null` will require adding short-circuits in PushButtonModel, StickyToggleButtonModel, etc. wherever `phetioEventSource` is used.  @samreid has a preference for using `null`, so he'll proceed with that.

(2) PhetioObject needs a couple of additional assertions in `initializePhetioObject`.  I didn't have time to do this, @samreid could you please handle?  Relevant code:

```js
      // @public (read-only) - the unique tandem for this instance
      // TODO: rename to this.tandem after all other this.*tandems deleted
      // TODO: do we need phetioID if we have phetioObjectTandem?
      this.phetioObjectTandem = options.tandem;
      assert && assert( this.phetioObjectTandem, 'phetioObjectTandem is required for initialization' );

      // @private - the IO type associated with this instance
      this.phetioType = options.phetioType;
      assert && assert( this.phetioType, 'phetioType is required for initialization' );
```

(3) We started to discuss whether something that extends PhetioObject must be initialized before use -- we think yes.  If so, how to enforce that? Is it sufficient to add assertions to all PhetioObject methods, so that they fail if called before initialization? What about uninitialized fields?  @samreid suggested setting a timer at the end of constructor that verifies initialization, I have concerns about impact of that approach.

**Comment by pixelzoom** [comment] 2018-02-08 20:25
(1) above seems relevant to this issue.  (3) should probably be factored out into a new issue.

**Comment by samreid** [comment] 2018-02-09 06:03
I committed the change for (1) above.  There is a problem with (2), I tried running it and ran into failures in phet brand, which causes phetioTypes to come up as undefined (because they load with the `ifphetio` plugin.)  Hence we cannot require them to exist (given the way things are currently done).  I think the most we can do now is require that the tandem be defined.

@pixelzoom you can reproduce the problem by making the change you proposed in (2) then running any simulation in PhET brand with assertions enabled.

I'll create a new issue in tandem for (3).

Let's discuss (2) here, and any review/follow-up discussion for (1).

**Comment by pixelzoom** [comment] 2018-02-09 16:41
`phetioType` is an option that is passed through to phetio.js via `tandem.addInstance`.  This assignment appears in PhetioObject `initializePhetioObject`:

```js
      // @private - the IO type associated with this instance
      this.phetioType = options.phetioType;
```

If annotation is `@private`, and `phetioType` is not used anywhere in PhetioObject.  So I believe this assignment should be removed.

**Comment by pixelzoom** [comment] 2018-02-09 16:42
It’s not at all obvious that PhetioObject DEFAULTS are the options for phetio.js.  And these defaults are duplicated in PhetioObject DEFAULTS and phetio.js PHET_IO_INSTANCE_OPTIONS:

```js
phetioState: false, // To include the instance in the state
phetioReadOnly: false, // When true, you can only get values from the instance; no setting allowed.
phetioInstanceDocumentation: '' // Useful notes about an instrumented instance, shown in instance-proxies
```

`phetioEvents`, on the other hand, is present in phetio.js PHET_IO_INSTANCE_OPTIONS, but missing from PhetioObject DEFAULTS.

Is `phetioEvents` inadvertently missing from PhetioObject DEFAULTS? Should PhetioObject and phetio.js should both be using (and sharing?) a complete set of defaults.

**Comment by pixelzoom** [comment] 2018-02-09 16:44
Above I said:
> `phetioType` is an option that is passed through to phetio.js via `tandem.addInstance`.

Investigating these options more... It’s not at all obvious that PhetioObject DEFAULTS are the options that are passed through to phetio.js via tandem.addInstance.  And these defaults are duplicated in PhetioObject DEFAULTS and phetio.js PHET_IO_INSTANCE_OPTIONS:

```js
phetioState: false, // To include the instance in the state
phetioReadOnly: false, // When true, you can only get values from the instance; no setting allowed.
phetioInstanceDocumentation: '' // Useful notes about an instrumented instance, shown in instance-proxies
```

`phetioEvents`, on the other hand, is present in phetio.js PHET_IO_INSTANCE_OPTIONS, but missing from PhetioObject DEFAULTS.

Is `phetioEvents` inadvertently missing from PhetioObject DEFAULTS? Should PhetioObject and phetio.js should both be using (and sharing?) a complete set of defaults.

**Comment by pixelzoom** [comment] 2018-02-09 17:07
Going still deeper...  Why are options passed to `tandem.addInstance`?  Shouldn't these options be fields in PhetioObject?  And shouldn't the instance passed to `tandem.addInstance` be an instanceof PhetioObject?

**Comment by pixelzoom** [comment] 2018-02-09 17:31
@samreid and I discussed via phone.  The plan is:

• PhetioObject becomes responsible for all phetio* options. Move all phetio options to PhetioObject, DEFAULTS, and (on initialization) they become instance fields.
• Remove PHET_IO_INSTANCE_OPTIONS and options from phetio.js.  
• In phetio.js, replace uses of `phetio.getOptions` with `phetio.getInstance`.  Delete `getOptions`.
• Change Tandem `addInstance` signature to `addInstance( instance )`, and `assert( instance instanceof PhetioObject )`.

**Comment by samreid** [comment] 2018-02-09 17:32
Thanks, I opened a new issue in https://github.com/phetsims/phet-io/issues/1304 and will move your notes there.

**Comment by pixelzoom** [comment] 2018-02-09 17:35
I think we're probably done with the `phetioEventSource` issue, and tangents are tracked in other issues.  So we can probably close this.  @samreid please close if you agree.

**Closed** 2018-02-12 18:01 UTC
Labels: dev:phet-io
