### ISSUE TITLE
ComboBox PhET-iO design pattern

### ISSUE THREAD

**Issue by arouinfar** [phetsims/sun#587] opened 2020-04-06 21:02 UTC
Several sims currently undergoing PhET-iO instrumentation contain ComboBox, see: 
* https://github.com/phetsims/ph-scale/issues/92
* https://github.com/phetsims/projectile-motion/issues/177
* https://github.com/phetsims/states-of-matter/issues/245

In design reviews @kathy-phet and I have discussed the general pattern what we would like featured in a ComboBox. If any of these requests are better handled on a sim-by-sim basis in the overrides, please let me know.

We would like the following to be phetioFeatured: true
- [x] `comboBox.displayOnlyProperty`
- [x] `comboBox.enabledProperty`
- [x] `comboBox.visibleProperty`
- [x] `comboBox.listBox.*.visibleProperty`

If possible, make these phetioFeatured: false
- [x] `comboBox.button.enabledProperty`
- [x] `comboBox.button.visibleProperty`

We also have some concerns regarding the ListBox. It seems like the `listBox.opacityProperty` and `listBox.pickableProperty` should be phetioReadOnly: true. However, they don't appear to be listening to the parent `comboBox.opacityProperty` and `comboBox.pickableProperty`, so it's possible for the ComboBox and ListBox to have different opacities. Similarly, it's possible to make the ComboBox unpickable, but the ListBox is still pickable. Both of these scenarios seem odd and undesirable to us.

- [x] `comboBox.listBox.visibleProperty` should be `phetioReadOnly: true` since the ListBox should only appear through interaction with the button.

**Comment by arouinfar** [comment] 2020-04-08 19:06
@kathy-phet and I talked a bit more about this today, and `listBox.opacityProperty` and `listbox.pickableProperty` are not high priority since these properties are not exposed to the client.

Addressing the checkboxes in https://github.com/phetsims/sun/issues/587#issue-595425648 should be the priority for this issue.

**Comment by arouinfar** [comment] 2020-04-15 22:16
@zepumph @samreid @chrisklus this issue needs to be addressed before delivering a dev version of ph-scale to the client.

**Comment by zepumph** [comment] 2020-04-15 22:47
>comboBox.enabledProperty

Currently this is only supported for default enabledProperties. In all three sims above it looks like comboboxes are not being passed a premade enabledProperty. So this will be good. I don't want to build out any more logic in ComboBox for this because it will be fixed when we use `EnabledNode` as a trait to add the `enabledProperty` instead.


>We also have some concerns regarding the ListBox. It seems like the listBox.opacityProperty and listBox.pickableProperty should be phetioReadOnly: true. However, they don't appear to be listening to the parent comboBox.opacityProperty and comboBox.pickableProperty, so it's possible for the ComboBox and ListBox to have different opacities. Similarly, it's possible to make the ComboBox unpickable, but the ListBox is still pickable. Both of these scenarios seem odd and undesirable to us.

I would be simple enough to link the pickability and opacity of the listbox to the value of the property for the Combobox, but I would first want to make sure that this wasn't interferring with any patterns that may already be in place for ComboBox. I don't know much about `combobox` and as a result I'm a bit uncertain if that would cause problems.

**Comment by zepumph** [comment] 2020-04-15 23:08
All the checkboxes have been implemented above. 

All that remains is the above discussion point about linking opacity and pickability of the listbox to the combo box.

**Comment by zepumph** [comment] 2020-04-15 23:09
@arouinfar please review and remove the blocking label if all looks as you desire.

**Comment by arouinfar** [comment] 2020-04-16 05:31
Thanks @zepumph!

I noticed that `comboBox.button.visibleProperty` is still phetioFeatured: true in ph-scale and states-of-matter (and I suspect the other sims too). Can you make it false?

> Currently this is only supported for default enabledProperties. In all three sims above it looks like comboboxes are not being passed a premade enabledProperty. So this will be good. I don't want to build out any more logic in ComboBox for this because it will be fixed when we use EnabledNode as a trait to add the enabledProperty instead.

That seems reasonable to me. I'll make a note in case I run into a sim in the future where `comboBox.enabledProperty` needs to be featured in the overrides.

> I would be simple enough to link the pickability and opacity of the listbox to the value of the property for the Combobox, but I would first want to make sure that this wasn't interferring with any patterns that may already be in place for ComboBox.

Good to know. I think this may take may merit a bigger discussion, but it's not pressing for any of the PhET-iO dev deliveries.

**Comment by pixelzoom** [comment] 2020-04-16 15:50
Setting `comboBox.button.visibleProperty` to `phetioFeatured: false` is a blocking issue for ph-scale.  See https://github.com/phetsims/ph-scale/issues/163.

**Comment by pixelzoom** [comment] 2020-04-16 16:05
From Slack phet-io channel 4/15/20:

Kathy Perkins  4:16 PM
Hi PhET-iO team, Can someone work on this issue for Combo Box? It's blocking delivery of dev version of pH Scale to client:
https://github.com/phetsims/sun/issues/587
Note also that Studio issues block RC publication but not this dev delivery.
Thanks! - Amy and Kathy

**Comment by pixelzoom** [comment] 2020-04-16 16:06
From Slack phet-io channel 4/15/20:

Michael Kauzmann  4:48 PM
It would be nice to get a dev or two to comment on my second paragraph in https://github.com/phetsims/sun/issues/587#issuecomment-614317610. I won't proceed until we discuss that further. Everything else is simple and will be added shortly.





4:50
As stated in https://github.com/phetsims/sun/issues/587#issuecomment-611136989 though, this piece up for discussion is not high priority.

**Comment by pixelzoom** [comment] 2020-04-16 16:07
@zepumph if your second paragraph is this:
> I would be simple enough to link the pickability and opacity of the listbox to the value of the property for the Combobox, but I would first want to make sure that this wasn't interferring with any patterns that may already be in place for ComboBox. I don't know much about combobox and as a result I'm a bit uncertain if that would cause problems.

I'm not aware of anything in ComboBox (or it's subcomponents) that should interfere with that.  But there have been a lot of hands in ComboBox, and I haven't looked at it in awhile.  That sounds like the proper approach, so I would proceed with that.

**Comment by zepumph** [comment] 2020-04-16 16:10
>I noticed that comboBox.button.visibleProperty is still phetioFeatured: true in ph-scale and states-of-matter (and I suspect the other sims too). Can you make it false?/

Thanks! I see my typo in ComboBoxButton and will commit shortly. (with grunt updates).


>I'm not aware of anything in ComboBox (or it's subcomponents) that should interfere with that approach. But there have been a lot of hands in ComboBox, and I haven't looked at it in awhile. That sounds like the proper approach, so I would proceed with that.

I'm interested in pursuing this strategy, and think it is probably best to do that now while we are on this issue.

**Comment by zepumph** [comment] 2020-04-16 16:43
combo box button visibleProperty phetioFeatured false bug should be fixed above. 


In https://github.com/phetsims/sun/commit/954cf46e3d9c2f785e7d046d27e8385dd559185e I synced opacity and pickable of the listbox to the value of the ComboBox. I think my preference from here (if this is what we like and want to go with), is to make the listbox pickable/opactity Properties `phetioReadOnly`. I'll go ahead and implement that since it is in the top comment.

**Comment by zepumph** [comment] 2020-04-16 19:48
list box has read-only opacity and pickle Properties above. 

@pixelzoom can you please review https://github.com/phetsims/sun/commit/217dbaaf3814cc094e51b237f7699b4eb24efa48

That is one-directional, but, when coupled with the fact that on the PhET-iO API the list box's Properties are read-only, I think that it is sufficient.

**Comment by pixelzoom** [comment] 2020-04-16 22:32
I verified that that `comboBox.button.visiblityProperty` is `phetioReadOnly: false`.

I verified changing `comboBox.opacityProperty` results in the same change to `comboBox.listbox.opacityProperty`.

Changing `comboBox.pickableProperty` results in the same change to `comboBox.listbox.pickableProperty`.  I'm not sure why this was necessary or desirable, because the only way to popup the listbox is to press the button, so this feels list unnecessary complication.  But in any case, I can still select items in the listbox. @arouinfar is that what was intended?   My recommendation would be to remove the linkage between `pickableProperty`.

**Comment by arouinfar** [comment] 2020-04-17 20:11
> Changing `comboBox.pickableProperty` results in the same change to `comboBox.listbox.pickableProperty`. I'm not sure why this was necessary or desirable, because the only way to popup the listbox is to press the button, so this feels like unnecessary complication. But in any case, I can still select items in the listbox. @arouinfar is that what was intended? My recommendation would be to remove the linkage between `pickableProperty`.

The behavior is definitely a bit funky. Now that`comboBox.listBox.visibleProperty` is read-only, I'm less convinced that the listbox needs to listen to the parent `pickableProperty`. I think it would fine to remove the linkage.

**Comment by pixelzoom** [comment] 2020-04-17 20:14
@zepumph sounds like it would be OK to remove the linkage for `pickableProperty`.  If you don't have any objections, could you make it so?

**Comment by zepumph** [comment] 2020-04-30 23:59
That is a very great call. Thanks you two!

**Closed by zepumph** 2020-04-30 23:59 UTC
Labels: design:phet-io, dev:phet-io, priority:2-high, status:blocks-sim-publication, status:ready-for-review
