### ISSUE TITLE
add titleAlignY to AccordionBox

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#159] opened 2015-02-27 22:52 UTC
Requested to support a feature in https://github.com/phetsims/least-squares-regression/issues/30.

Add options.titleAlignY to sun.AccordionBox, which controls vertical alignment of title relative to expand/collapse button.

> titleAlignY: 'center' // vertical alignment of button and title, 'top'|'center'

Will also need to rename the existing `titleAlign` option to `titleAlignX`.

**Comment by pixelzoom** [comment] 2015-02-27 23:16
Implementation completed. Assigning to @bereaphysics to review.

**Comment by bereaphysics** [comment] 2015-02-27 23:45
Looks good, thanks @pixelzoom. Closing.

**Closed by bereaphysics** 2015-02-27 23:45 UTC

**Comment by jonathanolson** [comment] 2015-02-28 18:42
@pixelzoom, can you verify that my change above is what was intended? The default 'center' was erroring on anything that didn't override titleAlignY.

**Comment by pixelzoom** [comment] 2015-02-28 21:17
@jonathanolson yes, that was a copy-paste error, thanks for catching, sorry for forgetting to test with 'ea'.

**Comment by jonathanolson** [comment] 2015-03-01 01:06
No worries, I'm just running automated tests more and it was pretty easy to spot.
