### ISSUE TITLE
Add support for popups to be "in front"

### ISSUE THREAD

**Issue by samreid** [phetsims/sun#238] opened 2016-04-25 16:33 UTC
From https://github.com/phetsims/sun/issues/229#issuecomment-214430328

> Having popups in front is [not] a general need that's exclusive to combo box -- it's needed by other things, like menus and dialogs. Imo we need an approach that is shared by all popups, including combo box.

**Comment by pixelzoom** [comment] 2018-12-30 02:14
Duplicate of #347, closing.

**Closed by pixelzoom** 2018-12-30 02:14 UTC
