### ISSUE TITLE
ComboBoxListBox scaling can be buggy with long strings

### ISSUE THREAD

**Issue by zepumph** [phetsims/sun#542] opened 2019-11-15 01:50 UTC
This is the general issue from initial investigation over in https://github.com/phetsims/molarity/issues/152.

@twant and I found that when combobox item lengths cause scaling to occur in the combobox button, the `Combobox.scaleListBox()` function doesn't work 100% of the time. It may be easiest to describe this in terms of examples:

--------------------------------------------
**Molarity**

When using `stringTest=long`, the listbox would be scaled wrong and as a result the `moveListBox` function wouldn't work either (it is called right afterwards). See https://github.com/phetsims/molarity/issues/152#issue-504768068

In this case, we were able to fix it by removing the `maxWidth` on the `listBox` parent. We still don't know the underlying cause. Another way that we could solve this, was by adding a `maxWidth` to each Text passed to a `ComboBoxItem`. We elected against that though.

-------------------------------------------------------

**States of Matter**

The ComboBox in states of matter isn't effectedby this bug. We thought that it was because the ComboBoxItem Text has a `maxWidth` (a solution for Molarity), but alas changing that doesn't matter, even when we set a maxWidth to the `ComboBox`.

-----------------------------------------------------------

**Beers Law Lab**

In this sim, we also get the bug (try `stringTest=long`), but this time, removing the maxWidth from the listBox parent did not solve things. 

--------------------------------------

@twant also noted that in dev versions before the major ComboBox overhaul last winter, this bug was not present. Assigning to @pixelzoom to see if he has any ideas or wants to collaborate on this.

**Comment by zepumph** [comment] 2019-11-15 01:51
Above is the workaround commit that worked for molarity, but not for beers-law-lab.

**Comment by pixelzoom** [comment] 2019-11-15 02:15
I'll have a look, but can't get to this until next week.

That workaround in https://github.com/phetsims/molarity/commit/244e74ed9c27b2c625ae9cb3d2435fd411fc6369 really doesn't look like something that should be committed to the production version of ComboBox.

**Comment by pixelzoom** [comment] 2019-11-15 17:36
OK, now that I'm not trying to look at this on my phone, I see that https://github.com/phetsims/molarity/commit/244e74ed9c27b2c625ae9cb3d2435fd411fc6369 is specific to MolarityScreenView,  so won't affect other sims.

**Comment by pixelzoom** [comment] 2019-11-15 17:41
After backing out phetsims/molarity@244e74e, I can reproduce in Molarity.  Interesting that if you open the list box 4 times, the problem corrects itself.  For the first 3, the listbox is not only in the wrong position, but scaled incorrectly.  For >=4 (tested up to 20),the listbox is positioned and scaled correctly.

**Comment by pixelzoom** [comment] 2019-11-15 17:50
In Beer's Law Lab with `stringTest=long`, I see similar behavior. But there's an additional problem that was not reported by @zepumph above. In the Concentration screen, clicking on the ComboBoxButton does not open the listbox until the 3rd time you click it. As in Molarity, the listbox is in the wrong position and scaled incorrectly.  On >= 4 clicks, the listbox is scaled and positioned correctly (also as in Molarity).

In the Beer's Law screen (either immediately after starting the sim, or after testing Concentration screen), on the 1st click the listbox opens in the wrong position and is scaled incorrectly. On >= 2nd click, the position and scaling are correct.

**Comment by pixelzoom** [comment] 2019-11-15 18:03
About BLL, @z said:
> In this sim, we also get the bug (try `stringTest=long`), but this time, removing the maxWidth from the listBox parent did not solve things.

I suspect that you many have been removing it from the listbox parent for the wrong screen.   There are 2 screens in this sim, each with its own listbox parent. If I remove  `maxWidth` for the listbox parent in both screens, the problem is resolved for both screens (pushed in above commit).

**Comment by pixelzoom** [comment] 2019-11-15 18:07
Same problem observed in pH Scale, which has 2 listbox parents in 2 screens.  Same fix works here, see before and after below.  Committed above.

Before - incorrect position and scale
<img width="449" alt="screenshot_1698" src="https://user-images.githubusercontent.com/3046552/68965008-ffb92000-0797-11ea-9df5-13364ee354b6.png">

After - correct position and scale
<img width="419" alt="screenshot_1699" src="https://user-images.githubusercontent.com/3046552/68965024-0cd60f00-0798-11ea-9425-4a1f9b978579.png">

**Comment by pixelzoom** [comment] 2019-11-15 18:20
So here's what's going on...  

First of all, the listbox parent shouldn't be setting `maxWidth`, because scaling and position the listbox is the responsibility of the ComboBox. It scales the listbox to match the button, and position the listbox relative to the button.   So setting `maxWidth` on the listbox parent was (in retrospect) inappropriate. 

When a `maxWidth` is specified for the listbox parent, we have 2 things applying transforms too the listbox.  The listbox parent and the ComboBox are both scaling the listbox, and that also (indirectly) affects position.  So we get this funky scaling and positioning behavior that has been observed.  

I don't know why this problem sorts itself out after the listbox is opened 4+ times.  And I suspect that this is a new problem because of the total rewrite of ComboBox and its subcomponents.   The listbox is scaled in `ComboBox.scaleListBox`, and I don't see anything obviously wrong here.  `localToGlobalBounds` is being used for both the button and the listbox.  What I suspect is happening is that the listbox parent is applying a transform _after_ `scaleListBox` is called.  And we have no way to change that. 

What I recommend is to examine listbox parents in other sims, identify the ones that are setting `maxWidth`, and remove it.   I've done that for BLL and pH Scale above.  Unclear whether this needs to be patched in release branches, and republished -- that's a question for @arielphet.

**Comment by pixelzoom** [comment] 2019-11-15 18:49
Regular expression `new .*ComboBox\(` identifies all instantiations of ComboBox and its subclasses -- assuming that the subclass is named with a "ComboBox" suffix.   I inspected all of these, and did not identify any additional cases where `maxWidth` is set for the listbox parent.  So this problem appears to be isolated to molarity, beers-law-lab, and ph-scale (all sims that I wrote).

**Comment by pixelzoom** [comment] 2019-11-15 18:58
Molarity is already tracked in https://github.com/phetsims/molarity/issues/152.
BLL is now being tracked in phetsims/beers-law-lab#242.
pH scale is now being tracks in phetsims/ph-scale#93.

We can decide what to do with these when the sims are next republished.  

Unassigning @ariel-phet.

**Comment by pixelzoom** [comment] 2019-11-15 18:58
@zepumph anything else to do here?

**Comment by pixelzoom** [comment] 2019-11-15 19:06
Btw... I did investigate whether ComboBox `scaleListBox` could be changed so that it works correctly if the listbox parent is scaled.   I thought I might be using the wrong coordinates transform, so tried replacing `localToGlobal` with `parentToGlobal`.   The result was even worse. Each time the listbox is opened, it scaled down more.   After 4 clicks, the Molarity combo box looks like this:

<img width="307" alt="screenshot_1700" src="https://user-images.githubusercontent.com/3046552/68968646-575b8980-07a0-11ea-827b-4f76cdca78ca.png">

**Comment by pixelzoom** [comment] 2019-11-16 03:14
That would be fine, and would catch other cases that I missed via manual inspection.  But note that there are other ways in which the listbox parent might be scaled that could cause similar buggy behavior.   And since this problem is not specific to i18n, I'd make the assertion message something like:

`'ComboBox is responsible for scaling listBox. Setting maxWidth for listParent may result in buggy behavior.'`

I would have added the assertion now, but I can't stick around to monitor CT.  If you want to add it, go for it. Otherwise I'll add it sometime late next week.

**Comment by pixelzoom** [comment] 2019-11-20 17:16
I've added the recommended assertion in the above commit, and I'll monitor CT.

**Comment by pixelzoom** [comment] 2019-11-20 18:46
Looks OK in CT.  

@zepumph anything else here? Feel free to close.

**Closed** 2019-11-20 21:50 UTC
Labels: type:bug
