### ISSUE TITLE
accessibleName and helpText API for ComboBox

### ISSUE THREAD

**Issue by twant** [phetsims/sun#503] opened 2019-04-29 23:55 UTC
In https://github.com/phetsims/molarity/issues/83, @zepumph and I were working on SoluteComboBox for Molarity, and were thinking about ways to implement help text for ComboBox. In noticing that ComboBoxButton is primarily responsible for setting the PDOM content of the entire element using the option `buttonLabelContent`, we overrode the setters for `accessibleName` and `helpText` in ComboBox that set the button's `labelContent` and `helpText` when these options are called for ComboBox. @jessegreenberg what do you think about this change? We are worried about overriding a Node prototype method.

**Comment by jessegreenberg** [comment] 2019-05-01 15:50
I am not to worried about overriding a Node method. But this also seems like a really good use case for `accessibleNameBehavior` and `helpTextBehavior`, I am wondering if those could be used here?

**Comment by zepumph** [comment] 2019-05-02 16:04
The reason why that isn't quite possible is because it is the ComboBoxButton that has all the accessibleContent. I'm unsure (because its untested) how it would work to have the accessibleNameBehavior set options on another Node. I will mark that as potential work to be done in https://github.com/phetsims/scenery/issues/867. Does that sound alright to you?

**Comment by jessegreenberg** [comment] 2019-05-02 16:17
Yes, that sounds great. I was naively thinking this:
```js
      // forward the accessible name to the button that opens this ComboBox, see ComboBoxButton for more info on
      // the naming relationship
      this.accessibleNameBehavior = ( node, options, accessibleName ) => {
        this.button.labelContent = accessibleName;
        return options;
      };
```
But understand that may not be how it was intended to be used.

**Comment by zepumph** [comment] 2019-05-02 16:30
See https://github.com/phetsims/scenery/issues/867, closing

**Comment by zepumph** [comment] 2020-08-18 21:24
Over in https://github.com/phetsims/sun/issues/444#issuecomment-675726001 and https://github.com/phetsims/scenery/issues/1070, a better pattern for setting accessibleName in ComboBox was determined. It should use accessibleNameBehavior instead of overriding `setAccessibleName`. This is just like what @jessegreenberg mentioned in https://github.com/phetsims/sun/issues/503. Let's reopen and clean this up.

**Comment by zepumph** [comment] 2020-08-19 16:51
I created a patch that is working in ComboBox, but it looks like there is a weird internal bug in the PDOMInstance Tree in which forwarding the accessibleName to a direct child throws an error because nesting PDOM updates causes the child to be manipulated in the tree before its parent HTMLElement exists yet (so we get an undefined error when trying to insertChild).

Here is a patch that uses behavior functions and works in ComboBox. I may just want to clean it up a bit.

```diff
Index: sun/js/ComboBox.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- sun/js/ComboBox.js	(revision ef901e4e0999b9a2322b886f5ce1190716f17ad5)
+++ sun/js/ComboBox.js	(date 1597795569837)
@@ -39,6 +39,26 @@
 const LIST_POSITION_VALUES = [ 'above', 'below' ]; // where the list pops up relative to the button
 const ALIGN_VALUES = [ 'left', 'right', 'center' ]; // alignment of item on button and in list
 
+// The definition for how ComboBox sets its accessibleName and helpText in the PDOM. Forward it onto its button. See
+// ComboBox.md for further style guide and documentation on the pattern.
+const ACCESSIBLE_NAME_BEHAVIOR = ( node, options, accessibleName ) => {
+  assert && assert( typeof accessibleName === 'string' );
+
+  // Support mutation before this is defined
+  if ( node.button ) {
+    node.button.accessibleName = accessibleName;
+  }
+  return options;
+};
+const HELP_TEXT_BEHAVIOR = ( node, options, helpText ) => {
+
+  // Support mutation before this is defined
+  if ( node.button ) {
+    node.button.helpText = helpText;
+  }
+  return options;
+};
+
 class ComboBox extends Node {
 
   /**
@@ -91,8 +111,9 @@
       closedNoChangeSoundPlayer: generalCloseSoundPlayer,
 
       // pdom
-      accessibleName: null, // the a11y setter for this is overridden, see below
-      helpText: null, // the a11y setter for this is overridden, see below
+      tagName: 'div',
+      accessibleNameBehavior: ACCESSIBLE_NAME_BEHAVIOR,
+      helpTextBehavior: HELP_TEXT_BEHAVIOR,
 
       // phet-io
       tandem: Tandem.REQUIRED,
@@ -138,13 +159,22 @@
       mouseAreaXDilation: options.buttonMouseAreaXDilation,
       mouseAreaYDilation: options.buttonMouseAreaYDilation,
 
-      // pdom - accessibleName and helpText are set via overridden functions on the prototype. See below.
+      // pdom - accessibleName and helpText are set via behavior functions on the ComboBox
 
       // phet-io
       tandem: options.tandem.createTandem( 'button' )
     } );
     this.addChild( this.button );
 
+    // TODO: to support passing accessibleName to a direct child, workaround
+    const pdomHeading = new Node( {
+      tagName: 'div',
+      accessibleOrder: [ this.button ]
+    } );
+    this.addChild( pdomHeading);
+
+    this.accessibleOrder = [ pdomHeading ];
+
     // put optional label to left of button
     if ( options.labelNode ) {
       this.button.left = options.labelNode.right + options.labelXSpacing;
@@ -326,25 +356,6 @@
 
   get enabled() { return this.getEnabled(); }
 
-  /**
-   * Instead of setting accessibleName on ComboBox, forward accessibleName setter to the button
-   * @param {string} accessibleName
-   * @public
-   * @override
-   */
-  setAccessibleName( accessibleName ) {
-
-    // set labelContent here instead of accessibleName because of ComboBoxButton implementation -- see that file for more details
-    this.button.labelContent = accessibleName;
-  }
-
-  /**
-   * Instead of setting accessibleName on ComboBox, forward helpText setter to the button
-   * @param {string} helpText
-   * @override
-   */
-  set helpText( helpText ) { this.button.helpText = helpText; }
-
   /**
    * Shows the list box.
    * @public
Index: scenery/js/accessibility/pdom/PDOMUtils.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- scenery/js/accessibility/pdom/PDOMUtils.js	(revision 414d42199d1e05b7d6d556462e908b006e623033)
+++ scenery/js/accessibility/pdom/PDOMUtils.js	(date 1597787954410)
@@ -406,7 +406,8 @@
    * @param {HTMLElement} [beforeThisElement] - if not supplied, the insertBefore call will just use 'null'
    */
   insertElements: function( element, childrenToAdd, beforeThisElement ) {
-
+    assert && assert( element instanceof HTMLElement );
+    assert && assert( Array.isArray( childrenToAdd ) );
     for ( let i = 0; i < childrenToAdd.length; i++ ) {
       const childToAdd = childrenToAdd[ i ];
       element.insertBefore( childToAdd, beforeThisElement || null );
Index: sun/js/ComboBoxButton.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- sun/js/ComboBoxButton.js	(revision ef901e4e0999b9a2322b886f5ce1190716f17ad5)
+++ sun/js/ComboBoxButton.js	(date 1597795569829)
@@ -25,6 +25,15 @@
 const ALIGN_VALUES = [ 'left', 'center', 'right' ];
 const ARROW_DIRECTION_VALUES = [ 'up', 'down' ];
 
+// The definition for how ComboBoxButton sets its accessibleName in the PDOM. See ComboBox.md for further style guide
+// and documentation on the pattern.
+const ACCESSIBLE_NAME_BEHAVIOR = ( node, options, accessibleName ) => {
+  options.labelTagName = 'span';
+  options.labelContent = accessibleName;
+  return options;
+};
+
+
 class ComboBoxButton extends RectangularPushButton {
 
   /**
@@ -59,10 +68,8 @@
       tandem: Tandem.OPTIONAL,
 
       // pdom
-      labelTagName: 'span',
       containerTagName: 'div',
-      labelContent: null // {string|null}
-
+      accessibleNameBehavior: ACCESSIBLE_NAME_BEHAVIOR
     }, options );
 
     assert && assert( _.includes( ALIGN_VALUES, options.align ),

```

**Comment by zepumph** [comment] 2020-08-25 23:04
After a discussion with @jessegreenberg and @jonathanolson today, we decided on a solution that put logic that forwarded to other Nodes into "callbacks" that were deferred until the PDOM content for a Node was created. This is working well in AccordionBox and ComboBox.

**Closed** 2020-08-25 23:07 UTC
Labels: dev:a11y, priority:2-high
