### ISSUE TITLE
Enabled/disabled mix-in

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/sun#19] opened 2013-09-05 17:09 UTC
See https://github.com/phetsims/scenery/issues/17 for more details and discussion, we don't want to add it directly to Scenery.

**Comment by pixelzoom** [comment] 2016-09-07 17:12
Duplicate of https://github.com/phetsims/sun/issues/257. Closing.

**Closed by pixelzoom** 2016-09-07 17:12 UTC
Labels: dev:enhancement
