### ISSUE TITLE
Improvements to Dialog default layout

### ISSUE THREAD

**Issue by zepumph** [phetsims/sun#525] opened 2019-09-16 20:17 UTC
From https://github.com/phetsims/gravity-force-lab/issues/144, @pixelzoom and I discussed a few ways to improve the default Dialog layout. Ideally it should be based on the screen dimensions, instead of including the nav bar as well. With this in mind, here is a working list of improvements:

- [x] Promote `Dialog.layoutStrategyCenteredInScreen` to the default layout strategy. A few questions still here. 
    * Do any Dialogs which to be centered on top of the whole sim (including the nav bar)? I think not.
    * No matter the answer to the above, should we still export that layout strategy so that it is central to Dialog and can be used if desired in the future?
- [x] Create a `DEFAULT_MAX_HEIGHT` and a `DEFAULT_MAX_WIDTH` that work well for i18n in the normal case, which are based on `ScreenView.DEFAULT_LAYOUT_BOUNDS`.
- [x] Remove usages of layoutStrategyCenteredInScreen since that will be default now.
- [x] Look through some dialogs to see if there is any more work to be done.
- [x] A related todo for this issue is marked to the issue `https://github.com/phetsims/gravity-force-lab/issues/144`

**Comment by zepumph** [comment] 2019-09-16 21:29
The first item was pretty straight forward, and I think it is a good change. Still to discuss:
- [ ] Should we keep the currently unused: `SIM_BOUNDS_CENTER_LAYOUT_STRATEGY`. I looked through all the usages, and it really seems like is we don't want to use it for nav/menu dialogs like about/keyboardHelop dialog, then we will never want it.

I then investigated making DEFAULT_MAX_HEIGHT/WIDTH constants, and basing them off of layout bounds from ScreenView, but this doesn't seem like a general solution. I don't know why we would provide such a default when there are 58 non default layoutBounds set in the project. Each of those would need to pass in their ScreenView to joist related code like AboutDialog, which seems very wrong.

Instead I was thinking that, by default, Dialog could look at the currently selected screen's `layoutBounds`, and set the maxWidth/Height dynamically based on that (as a default option). This way things would be general for all layout bounds. The issue that I'm finding though is how to override these settings. I'll work on a patch and see how I like things, I'm not sure this idea is ready to commit to master though.

**Comment by zepumph** [comment] 2019-09-17 02:02
I went down a bit of a rabbit whole trying to implement a default maxHeight and maxWidth. Much of this was spent talking with @jonathanolson about what the best api for dialog layout functions are. It seems like we want the default maxHeight and maxWidth to be based on the layoutBounds, but I couldn't figure out any way to do that. Here is a patch of my current progress.

I'm also curious about if we are trying to move dialogs to be so constrained to layoutBounds by default. I think it warrants further discussion.

<details>

```diff
Index: sun/js/Dialog.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- sun/js/Dialog.js	(revision 7edcb24c653ec76c6df829df68e324801dc136ab)
+++ sun/js/Dialog.js	(date 1568685672047)
@@ -39,6 +39,10 @@
   // constants
   const CLOSE_BUTTON_WIDTH = 14;
 
+  // The min distance from the top of the dialog to the dev bounds, same as the distance from the bottom of the dialog
+  // to the top of the navigation bar. Empirically determined
+  var EXTERNAL_MARGIN = 12;
+
   /**
    * @param {Node} content - The content to display inside the dialog (not including the title)
    * @param {Object} [options]
@@ -118,6 +122,9 @@
       fill: 'white', // {string|Color}
       stroke: 'black', // {string|Color}
       backgroundPickable: true,
+      maxHeight: null, // if not provided, then dynamically calculate based on the layoutBounds of the current screen, see updateLayoutMultilink
+      maxWidth: null, // if not provided, then dynamically calculate based on the layoutBounds of the current screen, see updateLayoutMultilink
+
       tandem: Tandem.optional,
       phetioType: DialogIO,
       phetioReadOnly: false, // default to false so it can pass it through to the close button
@@ -164,6 +171,11 @@
       phetioState: options.phetioState // match the state transfer of the Dialog
     } );
 
+    // keep track of if maxWidth and maxHeight were supplied by the client, because the default approach dynamically
+    // updates them based on the current screens layoutBounds.
+    const suppliedMaxHeight = options.maxHeight;
+    const suppliedMaxWidth = options.maxWidth;
+
     // create close button
     const closeButton = new CloseButton( {
 
@@ -233,7 +245,24 @@
 
     const sim = window.phet.joist.sim;
 
-    this.updateLayoutMultilink = Property.multilink( [ sim.boundsProperty, sim.screenBoundsProperty, sim.scaleProperty ], ( bounds, screenBounds, scale ) => {
+
+    this.updateLayoutMultilink = Property.multilink( [
+      sim.boundsProperty,
+      sim.screenBoundsProperty,
+      sim.scaleProperty,
+      sim.currentScreenProperty
+    ], ( bounds, screenBounds, scale, currentScreen ) => {
+
+      const currentScreenOrHomeScreen = currentScreen ? currentScreen : sim.homeScreen;
+      const screenView = currentScreenOrHomeScreen.view;
+      const globalScreenViewWidth = screenView.localToGlobalBounds( screenView.localBounds ).width;
+      const globalScreenViewHeight = screenView.localToGlobalBounds( screenView.localBounds ).height;
+      if ( !suppliedMaxHeight ) {
+        this.maxHeight = globalScreenViewHeight - EXTERNAL_MARGIN * 2;
+      }
+      if ( !suppliedMaxWidth ) {
+        this.maxWidth = globalScreenViewWidth - EXTERNAL_MARGIN * 2;
+      }
       if ( bounds && screenBounds && scale ) {
         options.layoutStrategy( this, bounds, screenBounds, scale );
       }
Index: joist/js/KeyboardHelpDialog.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- joist/js/KeyboardHelpDialog.js	(revision 6bf4c1b7b40c6b76bac9feb1034222981bbcdff8)
+++ joist/js/KeyboardHelpDialog.js	(date 1568685672042)
@@ -40,7 +40,6 @@
    * @constructor
    */
   function KeyboardHelpDialog( helpContent, options ) {
-
     options = _.extend( {
       titleAlign: 'center',
       fill: 'rgb( 214, 237, 249 )',
@@ -48,9 +47,7 @@
       tandem: Tandem.required,
 
       // Because of the special titleNode, we set the aria-labelledby attribute manually; see below.
-      addAriaLabelledByFromTitle: false,
-
-      maxHeight: 440 // TODO: copied from AboutDialog, see https://github.com/phetsims/gravity-force-lab/issues/144
+      addAriaLabelledByFromTitle: false
     }, options );
 
     // title
Index: joist/js/ScreenView.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- joist/js/ScreenView.js	(revision 6bf4c1b7b40c6b76bac9feb1034222981bbcdff8)
+++ joist/js/ScreenView.js	(date 1568675837083)
@@ -48,6 +48,10 @@
       //               the Play Area. This Node is added as a child to the ScreenSummaryNode
       screenSummaryContent: null
     }, options );
+
+    assert && assert( options.layoutBounds instanceof Bounds2 );
+
+    // @public (read-only) {Bounds2} - the bounds the confine the layout of the view.
     this.layoutBounds = options.layoutBounds;
 
     Node.call( this, _.extend( {
Index: joist/js/AboutDialog.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- joist/js/AboutDialog.js	(revision 6bf4c1b7b40c6b76bac9feb1034222981bbcdff8)
+++ joist/js/AboutDialog.js	(date 1568667430433)
@@ -32,10 +32,6 @@
   // Maximum width of elements in the dialog
   var MAX_WIDTH = 550;
 
-  // distance from the top of the about dialog to the dev bounds
-  // same as the distance from the bottom of the about dialog to the top of the navigation bar.
-  var EXTERNAL_MARGIN = 12;
-
   /**
    * @param {string} name - The name of the simulation
    * @param {string} version - The version of the simulation
@@ -202,14 +198,7 @@
       topMargin: 20,
       bottomMargin: 20,
       leftMargin: 20,
-      rightMargin: 20,
-
-      // This value was determined empirically and is suitable independent of the ScreenView.layoutBounds.  Scale the
-      // entire AboutDialog as a robust solution in case parts outside of the content resize in future versions. Note
-      // the layer containing the AboutDialog is already scaled based on the aspect ratio of the window. At a scale of
-      // 1.0, the amount of vertical space is 504 and the amount of space above the navigation bar is 464 because the
-      // navigation bar takes 40px at that scale.  Please see Sim.resizeAction for more details.
-      maxHeight: 464 - EXTERNAL_MARGIN * 2
+      rightMargin: 20
     } );
 
     // a11y - set label association so the title is read when focus enters the dialog
Index: coulombs-law/js/common/view/CoulombsLawKeyboardHelpContent.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- coulombs-law/js/common/view/CoulombsLawKeyboardHelpContent.js	(revision ab7079f7feb7f7f99445b85e1c0c52fe7e4c4e98)
+++ coulombs-law/js/common/view/CoulombsLawKeyboardHelpContent.js	(date 1568671245447)
@@ -14,8 +14,9 @@
   const CoulombsLawA11yStrings = require( 'COULOMBS_LAW/common/CoulombsLawA11yStrings' );
   const EndKeyNode = require( 'SCENERY_PHET/keyboard/EndKeyNode' );
   const GeneralKeyboardHelpSection = require( 'SCENERY_PHET/keyboard/help/GeneralKeyboardHelpSection' );
-  const KeyboardHelpSection = require( 'SCENERY_PHET/keyboard/help/KeyboardHelpSection' );
+  const HBox = require( 'SCENERY/nodes/HBox' );
   const HomeKeyNode = require( 'SCENERY_PHET/keyboard/HomeKeyNode' );
+  const KeyboardHelpSection = require( 'SCENERY_PHET/keyboard/help/KeyboardHelpSection' );
   const TwoColumnKeyboardHelpContent = require( 'SCENERY_PHET/keyboard/help/TwoColumnKeyboardHelpContent' );
 
   // strings
@@ -50,7 +51,7 @@
     constructor() {
 
       var helpContentOptions = {
-        
+
         // i18n, restricts both labelText and maxWidth, see KeyboardHelpSection
         labelMaxWidth: 130
       };
@@ -63,7 +64,7 @@
       const generalNavigationHelpContent = new GeneralKeyboardHelpSection( helpContentOptions );
       const adjustChargeContent = new AdjustChargeContent( helpContentOptions );
       KeyboardHelpSection.alignHelpSectionIcons( [ adjustChargeContent, generalNavigationHelpContent ] );
-      const rightHelpContent = [ adjustChargeContent, generalNavigationHelpContent ];
+      const rightHelpContent = [ new HBox( { children: [ adjustChargeContent, generalNavigationHelpContent ] } ),new HBox( { children: [ adjustChargeContent, generalNavigationHelpContent ] } ),new HBox( { children: [ adjustChargeContent, generalNavigationHelpContent ] } ),new HBox( { children: [ adjustChargeContent, generalNavigationHelpContent ] } ),new HBox( { children: [ adjustChargeContent, generalNavigationHelpContent ] } ), generalNavigationHelpContent ];
 
       super( leftHelpContent, rightHelpContent );
     }

```

**Comment by zepumph** [comment] 2019-10-08 01:07
I was finally able to crack this today. I was able to get the multilink in Dialog to play nicely with the current screen, and to set the maxHeight/Width, if not provided, to be based on the current screen's layout bounds. 

> Create a DEFAULT_MAX_HEIGHT and a DEFAULT_MAX_WIDTH that work well for i18n in the normal case, which are based on ScreenView.DEFAULT_LAYOUT_BOUNDS.

Instead of this checkbox, now it is dynamic, as described above.

I like this change quite a bit, as I think in general it looks better to center and focus Dialogs to be encapsulated in the screen instead of global on top of the screen and menu.


To test this you can go to `CoulombsLawKeyboardHelpContent` and replace the right section with:
```js
      const rightHelpContent = [ new HBox( { children: [ adjustChargeContent, generalNavigationHelpContent ] } ),new HBox( { children: [ adjustChargeContent, generalNavigationHelpContent ] } ),new HBox( { children: [ adjustChargeContent, generalNavigationHelpContent ] } ),new HBox( { children: [ adjustChargeContent, generalNavigationHelpContent ] } ),new HBox( { children: [ adjustChargeContent, generalNavigationHelpContent ] } ), generalNavigationHelpContent ];
```

and import the needed types. This will make a large keyboard dialog in coulombs law. 

@pixelzoom will you please review this issue as you have been a lead on Dialog for some time, and also made many recommendations for this issue over in https://github.com/phetsims/gravity-force-lab/issues/144#issuecomment-519144972.

**Comment by samreid** [comment] 2019-10-08 15:21
There are a few issues on CT this morning related to dialogs, I'm not sure of the cause but I noticed this issue and thought it may be related.  I'll mark as blocks publication until this is resolved.

**Comment by zepumph** [comment] 2019-10-08 17:15
There were two issues that came out of CT testing overnight. Sorry @samreid that you were roped into it. 

The first is that the maxHeight and width setters were sometimes subtracting the margins even when the total height/width was less than the margin. No negative maxHeight/Widths allowed.

The second was that in Gas Properties, the layout update is called because the sim has set the bounds/screenBounds Properties. In this case, just like was being done for the layoutStrategy function, we just guard against doing any work in that function until they are all defined (after first sim resize action is called).

Back to @pixelzoom for review.

**Comment by KatieWoe** [comment] 2019-10-08 19:22
Not sure if needed at this point, but a related issue is/was in sun that I missed this morning.

**Comment by pixelzoom** [comment] 2019-10-09 18:48
I skimmed the commits, and it seems to be working well for the `CoulombsLawKeyboardHelpContent` test suggested in https://github.com/phetsims/sun/issues/525#issuecomment-539269002.   It looks like the margins between the layoutBounds and Dialog edges is currently a constant (`DOUBLE_MARGIN`) and you might consider making that an option.

**Comment by pixelzoom** [comment] 2019-10-09 18:49
Removing label "blocks-publication" since the CT issues reported in https://github.com/phetsims/sun/issues/525#issuecomment-539565165 have been resolved.

**Comment by pixelzoom** [comment] 2019-10-11 14:56
Dialog sizing is seriously messed up. See https://github.com/phetsims/sun/issues/532. Adding label "blocks-publication".

**Comment by zepumph** [comment] 2019-10-11 18:29
This issue was that I was calculating maxHeight/Width based on the screen's localBounds, instead of the layoutBounds. This was problematic mainly for demo cases because sometimes there aren't items in the screen view in those sims. The change above gets the bounds of the layoutBounds and applies to the scale to that instead. 

Thanks @pixelzoom for posting your investigation over in https://github.com/phetsims/sun/issues/532. It helped me diagnose the problem, and fix it much easier!

I tested in the following ways:
* Ran the Gas Properties test in https://github.com/phetsims/sun/issues/532#issuecomment-541098219 and found that the dialogs are now the same size
* Added the CL keyboard help dialog test from https://github.com/phetsims/sun/issues/525#issuecomment-539565165 and saw that it had a good maxWidth/Height.
* Fuzzed sun demo with `?screens=4` when commenting out the guts of `MemoryTestsScreenView.step` (thanks @samreid from https://github.com/phetsims/joist/issues/582#issuecomment-540234250. This could reliably cause an error before the above fix.
* Went to sun and scenery-phet demo dialogs and saw that they are back to a normal size.

Would you please review @pixelzoom.

**Comment by pixelzoom** [comment] 2019-10-11 21:05
Self assigning so I remember to review.

**Comment by pixelzoom** [comment] 2019-10-14 23:11
I reviewed the commitm, and did some (but not all) of the tests listed in https://github.com/phetsims/sun/issues/525#issuecomment-541174745.  Seems like the problem is fixed.

**Comment by zepumph** [comment] 2019-10-14 23:38
Thanks @pixelzoom, next I'll tweak the margin constant into an option like https://github.com/phetsims/sun/issues/525#issuecomment-540137737 says.

**Comment by zepumph** [comment] 2019-10-18 00:28
Added the option above. Anything else here @pixelzoom?

**Comment by pixelzoom** [comment] 2019-10-18 00:35
👍 closing.

**Closed by pixelzoom** 2019-10-18 00:35 UTC
Labels: dev:a11y, status:ready-for-review, type:misc
