### ISSUE TITLE
Dispose is required for together

### ISSUE THREAD

**Issue by samreid** [phetsims/sun#170] opened 2015-04-03 18:16 UTC
Dispose is required, so that we can unregister components from together.js.  I'll have a go at it.

**Comment by samreid** [comment] 2015-04-03 18:17
Just planning to implement dispose for the components we are currently testing (with removal) in together:  RectangularButtons and RadioButtons.

**Comment by samreid** [comment] 2015-04-03 18:20
Added some disposes() above.

**Comment by pixelzoom** [comment] 2015-04-03 19:27
The dispose calls that you've added introduce memory leaks in the buttons. 

RadioButton links to `property`, and you need to unlink from `property` in dispose.

RectangularButtonView (and its inner appearance strategy) links to `interactionStateProperty`.

These need to be unlinked in dispose.

**Comment by pixelzoom** [comment] 2015-04-03 19:29
In RectangularPushButton:

```js
    dispose: function() {
      this.buttonModel.dispose();
      RectangularButtonView.prototype.dispose.call( this );
    },
```

Why is the supertype dispose called last? When overriding and chaining, supertype is typically called first in the chain.  If it's necessary to do otherwise, please add a comment explaining why.

**Comment by pixelzoom** [comment] 2015-04-03 19:34
In RectangularButtonView, the contentAppearanceStrategy will need a dispose function. And since the contentAppearanceStrategy can be provided as an option, you'll need to verify that it implements dispose before calling contentAppearanceStrategy.dispose.

**Comment by pixelzoom** [comment] 2015-04-03 19:35
Related to https://github.com/phetsims/sun/issues/121 (UI components that link to Property can result in memory leak).

**Comment by samreid** [comment] 2015-04-03 19:47
@pixelzoom said:

> The dispose calls that you've added introduce memory leaks in the buttons.
> RadioButton links to property.
> RectangularButtonView (and its inner appearance strategy) links to interactionStateProperty.
> These need to be unlinked in dispose.

Just to clarify.  Here is the code I added for RadioButton:

```js
  return inherit( Node, RadioButton, {
    dispose: function() {
      together && together.removeComponent( this );
    }
  } );
```

Does this dispose call I've added introduce a memory leak?  If so, how?

**Comment by samreid** [comment] 2015-04-03 19:52
Perhaps you meant it would mask a memory leak?

**Comment by pixelzoom** [comment] 2015-04-03 20:00
The contract for the dispose function is that it will properly clean up the object. These functions do not meet that contract.  If the client is using dispose to manage memory, then these functions cause a memory leak.

**Comment by pixelzoom** [comment] 2015-04-03 20:02
The fact that these UI components did not have a dispose function previously was also a problem. But in that case, the cause of the memory leak was faulty client code.  Now that these UI components have a dispose function, there is an additional fault, in the UI components themselves.

**Comment by samreid** [comment] 2015-04-09 19:00
I experimented with removing all listeners for RadioButton.js.  @pixelzoom is this what you had in mind?  How should we test this, or just use code inspection?  I'm also concerned that adding more fields to the instance (for access during the dispose) could cause collisions with other existing fields (or fields that will be added in the future).

```js
// Copyright 2002-2013, University of Colorado Boulder

/**
 * Base class for radio buttons.
 *
 * @author Chris Malley (PixelZoom, Inc.)
 */
define( function( require ) {
  'use strict';

  // modules
  var ButtonListener = require( 'SCENERY/input/ButtonListener' );
  var inherit = require( 'PHET_CORE/inherit' );
  var Node = require( 'SCENERY/nodes/Node' );
  var Rectangle = require( 'SCENERY/nodes/Rectangle' );

  /**
   * @param {Property} property
   * @param {*} value the value that corresponds to this button, same type as property
   * @param {Node} selectedNode node that will be displayed when the button is selected
   * @param {Node} deselectedNode node that will be displayed when the button is deselected
   * @param {Object} [options]
   * @constructor
   */
  function RadioButton( property, value, selectedNode, deselectedNode, options ) {

    options = _.extend( {
      cursor: 'pointer',
      focusable: true,
      togetherID: null
    }, options );

    this.togetherID = options.togetherID;

    var thisNode = this;
    Node.call( thisNode );
    this.property = property;

    //Add an invisible node to make sure the layout for selected vs deselected is the same
    var background = new Rectangle( selectedNode.bounds.union( deselectedNode.bounds ) );
    selectedNode.pickable = deselectedNode.pickable = false; // the background rectangle suffices

    thisNode.addChild( background );
    thisNode.addChild( selectedNode );
    thisNode.addChild( deselectedNode );

    // sync control with model
    this.propertyLinkListener = function( newValue ) {
      selectedNode.visible = ( newValue === value );
      deselectedNode.visible = !selectedNode.visible;
    };
    property.link( this.propertyLinkListener );

    // set property value on fire
    this.buttonListener = new ButtonListener( {
      fire: function() {
        var messageIndex = arch && arch.start( 'user', thisNode.togetherID, 'fired', { value: value } );
        property.set( value );
        arch && arch.end( messageIndex );
      }
    } );
    thisNode.addInputListener( this.buttonListener );

    this.mutate( options );

    together && together.addComponent( this );
  }

  return inherit( Node, RadioButton, {
    dispose: function() {
      together && together.removeComponent( this );
      this.property.unlink( this.propertyLinkListener );
      this.removeInputListener( this.buttonListener );
    }
  } );
} );
```

**Comment by samreid** [comment] 2015-04-13 23:27
If we follow through with https://github.com/phetsims/together/issues/72 then removeComponent() likely will not be within sun.

**Comment by pixelzoom** [comment] 2015-04-17 17:56
@samreid wrote:
> If we follow through with phetsims/together#72 then removeComponent() likely will not be within sun.

So the programmer will need to remember to handle dispose and together de-registration independently?

**Comment by samreid** [comment] 2015-04-20 14:47
> So the programmer will need to remember to handle dispose and together de-registration independently?

Yes.  removeComponent() calls should be geographically nearby to the addComponent() calls.

**Comment by pixelzoom** [comment] 2015-05-22 17:24
@samreid @jbphet Is this issue still relevant? addComponent/removeComponent doesn't appear to exist anymore. Do they have new named?

**Comment by pixelzoom** [comment] 2015-05-22 17:30
I suspect that this is now tandem.addInstance and removeInstance. Please confirm.

**Comment by samreid** [comment] 2015-05-22 22:48
Yes, sim and library code will use tandem.add/removeInstance.

**Comment by samreid** [comment] 2015-05-26 23:56
> So the programmer will need to remember to handle dispose and together de-registration independently?

Tandem de-registration should happen in dispose implementations.  For instance, HSlider implements both like so:

```js
    // @private Called by dispose
    this.disposeHSlider = function() {
      thumbNode.dispose && thumbNode.dispose(); // in case a custom thumb is provided via options.thumbNode that doesn't implement dispose
      valueProperty.unlink( valueObserver );
      thisSlider.enabledProperty.unlink( enabledObserver );
      options.tandem && options.tandem.removeInstance( thisSlider );
    };

    thisSlider.mutate( options );

    options.tandem && options.tandem.addInstance( this );
  }

  inherit( Node, HSlider, {

    // Ensures that this object is eligible for GC.
    dispose: function() {
      this.disposeHSlider();
    },
```

Not sure what else remains to be done for this issue, @pixelzoom can you comment?

**Comment by pixelzoom** [comment] 2015-05-27 14:11
There are places where dispose is missing or buggy (e.g., https://github.com/phetsims/axon/issues/61), but I guess we'll address those as we hit them.  At least we have a pattern for when/where to call tandem.removeInstance.

Closing.

**Closed by pixelzoom** 2015-05-27 14:11 UTC
