### ISSUE TITLE
Keyboard traversal is broken when ComboBoxListBox contains invisible items or the order of items is changed.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#859] opened 2023-12-04 03:50 UTC
Discovered in https://github.com/phetsims/my-solar-system/issues/306 for https://github.com/phetsims/qa/issues/1008 ...

Keyboard traversal is broken when ComboBoxListBox contains invisible items. Since PhET-iO allow clients to show/hide listbox items, this is a serious problem that affects PhET-iO sims.  See  https://github.com/phetsims/my-solar-system/issues/306 for examples in my-solar-system and density.

Git history suggested that @jessegreenberg added keyboard input to ComboBoxListBox, so I'll start by assigning to him. This is high priority -- my-solar-system is in a dev test, and need to create the release branch as soon as possible after the dev test is completed.

There also will need to be an evaluation of which published PhET-iO sims contains this bug, and whether that an MR is needed. Density is definitely broken, and there may be others.

**Comment by pixelzoom** [comment] 2023-12-04 14:54
This line in ComboBoxListBox construtor is also wrong; it assumes that all items are initially visible:

```ts
this.visibleListItemNodes = listItemNodes.slice();
```

**Comment by pixelzoom** [comment] 2023-12-04 15:03
Fixed in the above commit. Tested in my-solar-system, density, and fourier-making-waves.   @jessegreenberg please review.

I don't follow how to test the use of `setItemVisible` in cck-dc, so @samreid please verify.

Next step will be to figure out what to do about published PhET-iO sims (like density) that have this bug.

**Comment by samreid** [comment] 2023-12-04 16:37
Should I take the time to get up to speed on this issue, and figure out to sufficiently test cck-dc? Or would it be ok to describe how @pixelzoom or @jessegreenberg could exercise `setItemVisible` in cck-dc? (Lab screen => Advanced => Add Real Bulbs checkbox).  Checking and unchecking that checkbox doesn't crash the sim, and I don't see any keyboard focus highlighting in the sim (probably not supported yet?)

**Comment by pixelzoom** [comment] 2023-12-04 17:04
I've identified which published sims have these problem. They are:

* density
* geometric-optics
* geometric-optics-basics
* greenhouse-effect 

Here's the process that I used to identify those sims:

PhET-iO API files for these sims contain the element "listBox", and therefore potentially have this problem.

* beers-law-lab
* buoyancy
* center-and-variability
* density
* energy-skate-park
* fourier-making-waves
* gas-properties
* gases-intro
* geometric-optics
* geometric-optics-basics
* greenhouse-effect
* keplers-laws
* models-of-the-hydrogen-atom
* molarity
* molecule-shapes
* molecule-shapes-basics
* my-solar-system
* ph-scale
* ph-scale-basics
* projectile-motion
* states-of-matter
* states-of-matter-basics

From that list, these sims have been published (have links at https://bayes.colorado.edu/dev/phet-io/latest/):

* beers-law-lab
* center-and-variability
* density
* geometric-optics
* geometric-optics-basics
* greenhouse-effect
* molecule-shapes
* molecule-shapes-basics
* ph-scale
* ph-scale-basics

From that list, these sims have alt input enabled (`supportsInteractiveDescription: true` in package.json):

* center-and-variability
* density
* geometric-optics
* geometric-optics-basics
* greenhouse-effect
 
Finally, from that list, these sims instrument `listBox.*.visibleProperty`, and therefore have this problem. This was determined by searching for "listBox" in Studio, and inspecting the instrumentation of items.  These are the sims that would benefit from an MR.

* density @jonathanolson 
* geometric-optics @pixelzoom 
* geometric-optics-basics @pixelzoom 
* greenhouse-effect @jbphet 

Assigning to @brent-phet and @kathy-phet to decided on whether to do an MR.

**Comment by pixelzoom** [comment] 2023-12-04 17:29
Blocks publication of sims, and creation of my-solar-system 1.3 release branch, until the code review portion of this issue is completed.

**Comment by pixelzoom** [comment] 2023-12-04 20:04
We have another problem with ComboBoxListBox, reported in https://github.com/phetsims/my-solar-system/issues/308.  PhET-iO allows you to change the order of items in the listBox.  ComboBoxListBox does not adjust the order of `this.visibleListItemNodes` (or `this.listItemNodes`!) to match the new order.   This will affect many more PhET-iO sims than the 4 identified in https://github.com/phetsims/sun/issues/859#issuecomment-1839087778.

@jessegreenberg How do you want to proceed with this?  If it were me, I'd investigate getting rid of `this.visibleListItemNodes` and use the order of ComboBoxListBox `content: VBox` to do the traversal.

**Comment by jessegreenberg** [comment] 2023-12-04 23:06
Here is a potential fix, but thought a review before checking into main would be better.

I had to replace `listItemNodes` because the order of that list got stale in the same way. @pixelzoom what do you think about this change?

<details>

```patch
Subject: [PATCH] focusPanDirection -> limitPanDirection, see https://github.com/phetsims/center-and-variability/issues/564
---
Index: js/ComboBoxListBox.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/ComboBoxListBox.ts b/js/ComboBoxListBox.ts
--- a/js/ComboBoxListBox.ts	(revision 77b9e080b04df4bd783dbc092c6e67b13f820d21)
+++ b/js/ComboBoxListBox.ts	(date 1701730941511)
@@ -40,8 +40,8 @@
 
 export default class ComboBoxListBox<T> extends Panel {
 
-  // Nodes that correspond to items in the list
-  private readonly listItemNodes: ComboBoxListItemNode<T>[];
+  // The container for list items which will be provided to the panel.
+  private readonly content: Node;
 
   private readonly disposeComboBoxListBox: () => void;
 
@@ -181,6 +181,8 @@
       yMargin: options.yMargin / 2
     } ) );
 
+    this.content = content;
+
     this.voiceOnSelectionNode = voiceOnSelectionNode;
 
     // variable for tracking whether the selected value was changed by the user
@@ -227,7 +229,7 @@
 
         // Only visible items can receive focus - using content children directly because PhET-iO may change
         // their order
-        const visibleItems = content.children.filter( child => child.visible );
+        const visibleItems = this.getAllListItemNodes().filter( child => child.visible );
 
         if ( keysPressed === 'escape' || keysPressed === 'tab' ) {
 
@@ -268,8 +270,6 @@
     } );
     this.addInputListener( keyboardListener );
 
-    this.listItemNodes = listItemNodes;
-
     this.disposeComboBoxListBox = () => {
       for ( let i = 0; i < listItemNodes.length; i++ ) {
         listItemNodes[ i ].dispose(); // to unregister tandem
@@ -309,11 +309,19 @@
     return this.getListItemNode( value ).visible;
   }
 
+  /**
+   * Returns all list item Nodes, as children of the list box content in the correct order which may have changed
+   * from PhET-iO.
+   */
+  private getAllListItemNodes(): ComboBoxListItemNode<T>[] {
+    return this.content.children as ComboBoxListItemNode<T>[];
+  }
+
   /**
    * Gets the ComboBoxListItemNode that corresponds to a specified value. Assumes that values are unique.
    */
   private getListItemNode( value: T ): ComboBoxListItemNode<T> {
-    const listItemNode = _.find( this.listItemNodes, ( listItemNode: ComboBoxListItemNode<T> ) => listItemNode.item.value === value )!;
+    const listItemNode = _.find( this.getAllListItemNodes(), ( listItemNode: ComboBoxListItemNode<T> ) => listItemNode.item.value === value )!;
     assert && assert( listItemNode, `no item found for value: ${value}` );
     assert && assert( listItemNode instanceof ComboBoxListItemNode, 'invalid listItemNode' ); // eslint-disable-line no-simple-type-checking-assertions
     return listItemNode;
@@ -323,19 +331,28 @@
    * Gets the item in the ComboBox that currently has focus.
    */
   private getFocusedItemNode(): ComboBoxListItemNode<T> {
-    const listItemNode = _.find( this.listItemNodes, ( listItemNode: ComboBoxListItemNode<T> ) => listItemNode.focused )!;
+    const listItemNode = _.find( this.getAllListItemNodes(), ( listItemNode: ComboBoxListItemNode<T> ) => listItemNode.focused )!;
     assert && assert( listItemNode, 'no item found that has focus' );
     assert && assert( listItemNode instanceof ComboBoxListItemNode, 'invalid listItemNode' ); // eslint-disable-line no-simple-type-checking-assertions
     return listItemNode;
   }
 
   /**
-   * Focuses the ComboBoxListItemNode that corresponds to a specified value
+   * Focuses the ComboBoxListItemNode that corresponds to a specified value. If the item for that value is not
+   * visible, focus is placed on the first visible item.
    */
   public focusListItemNode( value: T ): void {
-    const listItemNode = this.getListItemNode( value );
-    listItemNode.supplyOpenResponseOnNextFocus();
-    listItemNode.focus();
+    let listItemNode: ComboBoxListItemNode<T> | undefined = this.getListItemNode( value );
+
+    // If the item Node is not visible, just place focus on the first available item.
+    if ( !listItemNode.visible ) {
+      listItemNode = _.find( this.getAllListItemNodes(), ( listItemNode: ComboBoxListItemNode<T> ) => listItemNode.visible );
+    }
+
+    if ( listItemNode ) {
+      listItemNode.supplyOpenResponseOnNextFocus();
+      listItemNode.focus();
+    }
   }
 
   /**

```
</details>

**Comment by pixelzoom** [comment] 2023-12-04 23:35
@kathy-phet pointed out that only sims that support alt input are affected.  Sims that have been published, have an instrumented comboBox, and support alt input are:

* center-and-variability
* density
* geometric-optics
* geometric-optics-basics
* greenhouse-effect

**Comment by pixelzoom** [comment] 2023-12-06 00:19
@jessegreenberg Your patch looks and tests good, thanks!  I went ahead and committed it.

I think it would be worth having QA verify this change. @KatieWoe can you fit that in? 

To test:
* Run my-solar-system in Studio.
* Go to `orbitalSystemComboBox.listBox` in the Studio tree.
* Play around with changing `listBox.*Item.visibleProperty` for various items.
* Verify that keyboard navigation of the comboBox continues to work as expected.

**Comment by pixelzoom** [comment] 2023-12-06 20:12
This is ready for MR.   Adding @zepumph to assignees in case this can be added to the PhET-iO MR https://github.com/phetsims/phet-io/issues/1974.

**Comment by zepumph** [comment] 2023-12-06 23:25
>This is ready for MR. Adding @zepumph to assignees in case this can be added to the PhET-iO MR https://github.com/phetsims/phet-io/issues/1974.

Can you please tell me what commits go to what sims?

**Comment by zepumph** [comment] 2023-12-15 21:47
Excellent. This doesn't need to be patched into MSS 1.3 because this fix occurred before the RC was taken.

**Comment by zepumph** [comment] 2023-12-15 23:04
I'm having a bit of a hard time feeling confident about the provided list of sims that need the fix. Furthermore, I'm worried about cherry picking selectively like that and then running into trouble in the next 2 combo box issues because some branches don't have this change in there and so cherry picking fails. 

I think I'd prefer a complete list of all hydrogen sims that use a combo box.

I tried to use binder for this, but I don't think I trust it, since it doesn't have CAV. Likely it isn't being tested with `?locales=*` so it isn't handling the region/culture combo box. So I think I recommend adding CAV to this list, and proceeding with this for all three combo box patches.

```
    "beers-law-lab",
    "concentration",
    "density",
    "geometric-optics",
    "geometric-optics-basics",
    "greenhouse-effect",
    "molecule-polarity",
    "molecule-shapes",
    "molecule-shapes-basics",
    "ph-scale",
    "ph-scale-basics"
```

**Comment by zepumph** [comment] 2023-12-15 23:31
I have gotten stuck. The last two patches didn't apply automatically and I think it will be fastest and easiest to work with @jessegreenberg sync to try to get this working.

**Comment by zepumph** [comment] 2023-12-18 18:46
This issue has been MR'd successfully. While we were working on this, @jessegreenberg and I found two other regressions in Combo box that need to be MR'd. Noted in the above issues, and the MR will occur separately in those side issues.

Next we are ready to test.

**Comment by zepumph** [comment] 2023-12-19 19:54
The above commits fixed a type error in ph-scale by importing Node (it was using the global, which doesn't have `children`)

**Comment by zepumph** [comment] 2024-01-03 16:55
This was confirmed fixed by QA for all MR sims with a Combo Box. Closing

**Closed by zepumph** 2024-01-03 16:55 UTC
Labels: type:bug, status:ready-for-review, dev:maintenance-release, dev:alt-input
