### ISSUE TITLE
How to support name/description for AccessibleNumberTweaker?

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/sun#357] opened 2018-05-14 19:30 UTC
It was a bit unclear whether to use innerContent or labelContent for the main "name" of the tweaker. Currently Area Model is passing `innerContent` in to a NumberPicker for this purpose, but I had a TODO note to check.

Given the desire for a bit of abstraction, how ideally would we want to specify the name and description for this?

**Comment by zepumph** [comment] 2018-05-25 22:48
This seems like a duplicate of https://github.com/phetsims/area-model-common/issues/150. In that issue we decided that it is best to use `labelContent`.  I suspect as abstractions develop, this will be revisited and trasferred to some sort of `accessibleName` and `helpText` api. Closing. If anyone feels like more is needed, please reopen.

**Closed** 2018-05-25 22:49 UTC
Labels: dev:a11y
