### ISSUE TITLE
Sun buttons do not resize correctly when their content has dynamic bounds.

### ISSUE THREAD

**Issue by samreid** [phetsims/sun#781] opened 2022-08-23 20:03 UTC
Discovered in https://github.com/phetsims/chipper/issues/1302 by @jonathanolson and reviewed by @samreid and @zepumph .

**Comment by zepumph** [comment] 2022-08-23 21:07
As part of this issue. It would be helpful if you could explain why the button didn't work, but a nested VBox did. I don't really understand that part.

**Comment by zepumph** [comment] 2022-08-26 20:23
I'm pretty sure this issue is just a duplicate of https://github.com/phetsims/sun/issues/783

**Comment by zepumph** [comment] 2022-08-26 20:24
Oops, didn't mean to close.

**Comment by pixelzoom** [comment] 2022-08-30 14:29
Not a duplicate of #783. This is a problem that is specific to #783.  And the resize behavior of sun buttons in general (not just push buttons that involve Text is incorrect, as reported in https://github.com/phetsims/sun/issues/783#issuecomment-1227843745.   So I'm going to generalize the title of this issue to reflect that.

**Comment by jonathanolson** [comment] 2022-08-31 17:24
Handled above. @samreid can you confirm?

**Comment by jessegreenberg** [comment] 2022-08-31 20:36
I am seeing some layout regressions in sun buttons and thought it could be related to this issue. For example
<details><summary>Radio buttons in moleculesl-and-light</summary>

![image](https://user-images.githubusercontent.com/6396244/187776864-4c0c6263-7191-4aa0-88cc-2db39d61c9b7.png)

</details>

<details><summary>Radio buttons in function-builder</summary>

![image](https://user-images.githubusercontent.com/6396244/187776966-c5595591-1919-4483-a3a5-57751a33040f.png)

</details>

<details><summary>Carousel buttons</summary>

![image](https://user-images.githubusercontent.com/6396244/187777046-826c69f8-1ef9-42fe-9b26-aec9eac7077c.png)

</details>

There may be more, but those were some examples I noticed.

**Comment by samreid** [comment] 2022-09-01 01:04
@jonathanolson can you please take the lead on the preceding comment before I review?

**Comment by jonathanolson** [comment] 2022-09-01 02:36
There was a flow for buttons setting specific sizes that wasn't handled, that should be fixed with the above commit.

**Comment by pixelzoom** [comment] 2022-09-01 21:07
Reviewed behavior in the context of Natural Selection, and button resize behavior is now as expected.  I did not review the code changes. Closing.

**Closed by pixelzoom** 2022-09-01 21:07 UTC
Labels: type:bug, priority:2-high, status:ready-for-review, status:blocks-publication
